export const alerts = [
  {
    id: "temp-floor-2w",
    status: "current",
    severity: "High",
    severityDot: "red",
    type: "temperature",
    title: "Temp Out (Floor 2 W) Temperature fell below 110°F",
    location: "Floor 2 (West)",
    locationIcon: "location_on",
    targetName: "Temp Out (Floor 2 W)",
    targetIcon: "thermometer",
    equipment: "DHW Tank (West)",
    sensorType: "Temperature Sensor",
    automation: "Legionella Risk",
    timeInAlertShort: "1 day, 4 hours, 19 mi...",
    timeInAlertFull: "1 day, 4 hours, 20 minutes",
    startTime: "03/25/26 11:03 EDT",
    cardIcon: "warning",
    headerIcon: "warning",
    timelineType: "temperature",
    readingValue: "101.8°F",
    readingDelta: "8.2°F lower than trigger",
    readingAsOf: "0min ago",
    thresholdLabel: "Threshold",
    legendLabel: "Temperature",
    yAxisLabels: ["102 °F", "100 °F", "98 °F"],
    xAxisLabels: ["15:00", "18:00", "21:00", "00:00", "03:00", "06:00", "09:00", "12:00", "15:00"],
    chartDateLabel: "Mar 26, 2026",
    timezone: "EDT",
    timelineEvents: [
      {
        id: "temp-event-1",
        date: "25 Mar",
        time: "11:03",
        title: "Temperature fell below 110°F",
        icon: "error",
        iconColor: "red",
      },
    ],
    notifications: [
      {
        icon: "mail",
        label: "Notify via Email",
        pills: ["1 Recipient"],
      },
    ],
  },
  {
    id: "comm-floor-1w",
    status: "current",
    severity: "High",
    severityDot: "red",
    type: "communication",
    title: "Temp Out (Floor 1 W) has lost communication",
    location: "Floor 1 (West)",
    locationIcon: "location_on",
    targetName: "Temp Out (Floor 1 W)",
    targetIcon: "thermometer",
    equipment: "Boiler Room Mixing",
    sensorType: "Temperature Sensor",
    automation: "Sensor Lost Communication",
    timeInAlertShort: "11 days, 23 hours, 3...",
    timeInAlertFull: "11 days, 23 hours, 34 minutes",
    startTime: "03/14/26 15:48 EDT",
    cardIcon: "signal_disconnected",
    headerIcon: "signal_disconnected",
    timelineType: "communication",
    timelineEvents: [
      {
        id: "comm-event-1",
        date: "14 Mar",
        time: "15:48",
        title: "Device has lost communication",
        icon: "error",
        iconColor: "red",
      },
    ],
    notifications: [
      {
        icon: "mail",
        label: "Notify via Email",
        pills: ["1 Recipient"],
      },
    ],
  },
  {
    id: "smart-base-station-1",
    status: "current",
    severity: "High",
    severityDot: "red",
    type: "communication",
    title: "Smart Base Station 1 has lost communication",
    location: "Floor 2 (West)",
    locationIcon: "location_on",
    targetName: "Smart Base Station 1",
    targetIcon: "router",
    equipment: "Relay 40000001 (Slot 2)",
    sensorType: "Pressure Sensor",
    automation: "Trident & Alarm Cycle",
    timeInAlertShort: "1 month, 3 days, 9 h...",
    timeInAlertFull: "1 month, 3 days, 9 hours, 52 minutes",
    startTime: "02/20/26 04:31 EST",
    cardIcon: "signal_disconnected",
    headerIcon: "signal_disconnected",
    timelineType: "communication",
    timelineEvents: [
      {
        id: "comm-event-2",
        date: "20 Feb",
        time: "04:31",
        title: "Device has lost communication",
        icon: "error",
        iconColor: "red",
      },
    ],
    notifications: [
      {
        icon: "mail",
        label: "Notify via Email",
        pills: ["1 Recipient"],
      },
    ],
  },
  {
    id: "sensor-30000005-leak",
    status: "current",
    severity: "High",
    severityDot: "red",
    type: "leak",
    title: "Sensor 30000005 has Leak Detected",
    location: "Floor 2 (West)",
    locationIcon: "location_on",
    targetName: "Sensor 30000005",
    targetIcon: "water_drop",
    equipment: "Leak Defense Oasis 2",
    sensorType: "Leak Detector",
    automation: "Trident & Alarm Cycle",
    timeInAlertShort: "1 month, 3 days, 20 ...",
    timeInAlertFull: "1 month, 3 days, 20 hours, 44 minutes",
    startTime: "02/19/26 17:39 EST",
    cardIcon: "warning",
    headerIcon: "warning",
    timelineType: "leak",
    timelineEvents: [
      {
        id: "leak-event-1",
        date: "19 Feb",
        time: "17:40",
        title: "Leak Cleared",
        icon: "event",
        iconColor: "gray",
      },
      {
        id: "leak-event-2",
        date: "19 Feb",
        time: "17:39",
        title: "Leak Detected",
        icon: "event",
        iconColor: "gray",
      },
      {
        id: "leak-event-3",
        date: "19 Feb",
        time: "17:39",
        title: "Notify Via Call",
        icon: "call",
        iconColor: "gray",
        pills: ["1 Recipient(s)", "24 hours"],
        badge: "Invalid phone number",
        meta: "Last called: Cade Testington",
        chevron: true,
      },
    ],
    notifications: [],
    notificationEmptyText: "No custom actions were defined.",
  },
  {
    id: "sensor-30000003-leak",
    status: "current",
    severity: "High",
    severityDot: "red",
    type: "leak",
    title: "Sensor 30000003 has Leak Detected",
    location: "Floor 2 (West)",
    locationIcon: "location_on",
    targetName: "Sensor 30000003",
    targetIcon: "water_drop",
    equipment: "Leak Defense Oasis 4",
    sensorType: "Leak Detector",
    automation: "Trident & Alarm Cycle",
    timeInAlertShort: "1 month, 3 days, 20 ...",
    timeInAlertFull: "1 month, 3 days, 20 hours, 44 minutes",
    startTime: "02/19/26 17:39 EST",
    cardIcon: "warning",
    headerIcon: "warning",
    timelineType: "leak",
    timelineEvents: [
      {
        id: "leak-event-4",
        date: "19 Feb",
        time: "17:40",
        title: "Leak Cleared",
        icon: "event",
        iconColor: "gray",
      },
      {
        id: "leak-event-5",
        date: "19 Feb",
        time: "17:39",
        title: "Leak Detected",
        icon: "event",
        iconColor: "gray",
      },
      {
        id: "leak-event-6",
        date: "19 Feb",
        time: "17:39",
        title: "Notify Via Call",
        icon: "call",
        iconColor: "gray",
        pills: ["1 Recipient(s)", "24 hours"],
        badge: "Invalid phone number",
        meta: "Last called: Cade Testington",
        chevron: true,
      },
    ],
    notifications: [],
    notificationEmptyText: "No custom actions were defined.",
  },
  {
    id: "fuel-puck-leak",
    status: "current",
    severity: "High",
    severityDot: "red",
    type: "leak",
    title: "Leak Sensor (Fuel Puck) has Leak Detected",
    location: "Plant 1 Pad",
    locationIcon: "location_on",
    targetName: "Leak Sensor (Fuel Puck)",
    targetIcon: "water_drop",
    equipment: "Plant 1",
    sensorType: "Leak Detector",
    automation: "Trident & Alarm Cycle",
    timeInAlertShort: "1 month, 3 days, 20 ...",
    timeInAlertFull: "1 month, 3 days, 20 hours, 47 minutes",
    startTime: "02/19/26 17:36 EST",
    cardIcon: "warning",
    headerIcon: "warning",
    timelineType: "leak",
    timelineEvents: [
      {
        id: "leak-event-7",
        date: "19 Feb",
        time: "17:39",
        title: "Leak Cleared",
        icon: "event",
        iconColor: "gray",
      },
      {
        id: "leak-event-8",
        date: "19 Feb",
        time: "17:36",
        title: "Leak Detected",
        icon: "event",
        iconColor: "gray",
      },
      {
        id: "leak-event-9",
        date: "19 Feb",
        time: "17:36",
        title: "Notify Via Call",
        icon: "call",
        iconColor: "gray",
        pills: ["1 Recipient(s)", "24 hours"],
        badge: "Invalid phone number",
        meta: "Last called: Cade Testington",
        chevron: true,
      },
    ],
    notifications: [],
    notificationEmptyText: "No custom actions were defined.",
  },
  {
    id: "resolved-example",
    status: "resolved",
    severity: "Low",
    severityDot: "orange",
    type: "communication",
    title: "Meter 3 communication restored",
    location: "Floor 2 (West)",
    locationIcon: "location_on",
    targetName: "Meter 3",
    targetIcon: "water",
    equipment: "Valve",
    sensorType: "Flow Meter",
    automation: "Resolved Alert",
    timeInAlertShort: "2 hours",
    timeInAlertFull: "2 hours",
    startTime: "03/01/26 10:00 EDT",
    cardIcon: "check_circle",
    headerIcon: "check_circle",
    timelineType: "communication",
    timelineEvents: [
      {
        id: "resolved-1",
        date: "01 Mar",
        time: "10:00",
        title: "Communication restored",
        icon: "check_circle",
        iconColor: "gray",
      },
    ],
    notifications: [
      {
        icon: "mail",
        label: "Notify via Email",
        pills: ["1 Recipient"],
      },
    ],
  },
];